name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.forgejo/workflows/renovate.yaml'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json5'
      - '.envrc'
      - '.gitignore'
      - 'default.nix'

jobs:
  docker:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set build tag
        shell: bash
        run: |
          echo "BUILD_TAG=main-${GITHUB_SHA:0:7}-$(date +%s)" >> $GITHUB_ENV

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: forge.internal
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_PASSWORD }}

      - name: Set up QEMU                                                                                                                                                  
        uses: docker/setup-qemu-action@v3                                                                                                                                  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."forge.internal"]
              http = true
              insecure = true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            forge.internal/nemo/ask:latest
            forge.internal/nemo/ask:${{ env.BUILD_TAG }}
